name: Lint
on:
  workflow_call:

# This requires the build job to have been ran first

jobs:
  code:
    runs-on: ubuntu-latest
    name: Lint Code
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm
      - uses: ./.github/actions/download-build
      - name: Lint
        run: pnpm run lint
  api:
    runs-on: ubuntu-latest
    name: Lint API
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm
      - uses: ./.github/actions/download-build
      - name: Lint
        run: pnpm run lint:api
  validate:
    runs-on: ubuntu-latest
    name: Validate API
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm
      - uses: ./.github/actions/download-build
      - name: Lint
        run: pnpm run lint:validate
