name: Lint
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  code:
    runs-on: ubuntu-latest
    name: Lint Code
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm
      - uses: ./.github/actions/download-build
      - name: Lint
        run: pnpm run lint
  api:
    runs-on: ubuntu-latest
    name: Lint API
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm
      - uses: ./.github/actions/download-build
      - name: Lint
        run: pnpm run lint:api
  validate:
    runs-on: ubuntu-latest
    name: Validate API
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm
      - uses: ./.github/actions/download-build
      - name: Lint
        run: pnpm run lint:validate
