name: Lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Code
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          version: latest
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
  lint-api:
    runs-on: ubuntu-latest
    name: Lint API
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          version: latest
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint:api
