name: Pull Request
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  lint:
    name: Lint
    needs: build
    uses: ./.github/workflows/lint.yml
