name: Push
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  lint:
    needs: [build]
    name: Lint
    uses: ./.github/workflows/lint.yml
  update-api-version:
    name: Update API Version
    uses: ./.github/workflows/update-api-version.yml
    needs: [lint]
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    needs: [update-api-version]
    with:
      commit: ${{ needs.update-api-version.outputs.commit }}
