name: Update API Version

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update-api-version:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts
        # https://github.com/mikefarah/yq/issues/515 - yq strips whitespace
        # https://github.com/mikefarah/yq/issues/515#issuecomment-1050637663
      - name: Update API Version
        uses: mikefarah/yq@v4
        with:
          cmd: |
            apk add --no-cache git patch
            SHA=$(git rev-parse --short master) yq ".info.version = strenv(SHA)" api/api.yaml > api/new.yaml
            yq '.' api/api.yaml > api/noblanks.yaml
            diff -B api/noblanks.yaml api/new.yaml > api/new.patch
            patch api/api.yaml api/new.patch
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Update API Version"
          file_pattern: "api/api.yaml"
          disable_globbing: true
